version: "3.8"

services:
  client:
    build:
      context: ./client/
      target: development
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000
  server:
    build: ./server/
    ports: 
      - '80:80'
    volumes:
      - ./server:/app

